---
name: Python Concepts Main Pipeline

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  pull_request:
    branches: [main]
    paths-ignore: [README.md]

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install PyLint, Flake8 and Black
        run: python -m pip install --user pylint flake8 black

      - name: Run PyLint
        run: python -m pylint *.py

      - name: Run Flake8
        run: python -m flake8 --ignore=E731 --max-line-length=88 *.py

      - name: Run Black
        run: python -m black --diff --check --color *.py

  tests:
    name: Tests
    needs: [syntax]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Pytest
        run: python -m pip install --user pytest

      - name: Run Pytest
        run: python -m pytest -v main.py
